---
title: "post_introduction_system"
author: "Maude Vernet"
date: "2025-05-23"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r set parameters}
divider <- 4*10^6

pre_species <- c("palm trees",
                 "seabirds",
                 "herbivorous crabs",
                 "carnivorous crabs",
                 "cane spiders",
                 "geckos",
                 "cockroaches",
                 "terrestrial arthropods",
                 "flying arthropods",
                 "native trees",
                 "others")
```


```{r add sihek}
source("../../EEMtoolbox_fork/adapted functions/add_introduced_species.R")

load("../pre_introduction/pre_EEM.RData")

post_EEM <- add_introduced_species(native_parameters = pre_EEM,
                                   introduced_upper_bound_growth_rate = 1.1,
                                   introduced_self_sign = -1,
                                   introduced_row_signs = 
                                     c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
                                   introduced_col_signs = 
                                     c(0, rep(-1, 8), 0, -1),
                                   introduced_k = 86/divider)

source("../../EEMtoolbox_fork/adapted functions/add_species_names.R")

post_EEM <- add_species_names(post_EEM,
                              c("sihek", pre_species))
```

```{r check if all parameters give eq within the bounds}
source("../../EEMtoolbox_fork/adapted functions/select_EEM_outputs.R")
load("../pre_introduction/initial abundances/pre_lb.RData")
load("../pre_introduction/initial abundances/pre_ub.RData")

select_EEM_outputs(post_EEM,
                   target_lower = c(85.999999, pre_lb)/divider,
                   target_upper = c(86.000001, pre_ub)/divider,
                   mode = "disturbed")
```

```{r calculate projections with control of both palm and sihek}
source("../../EEMtoolbox_fork/adapted functions/adapted_calculate_projections.R")
source("../../EEMtoolbox_fork/adapted functions/adapted_ode_solve.R")
source("../../EEMtoolbox_fork/adapted functions/extract_eq.R")

post_initial <- extract_eq(pre_EEM)
for(i in seq_len(length(post_EEM))) {
  post_initial[[i]] <- c(sihek = 0, 
                         "palm trees" = 32876/divider, 
                         post_initial[[i]][2:11])
}

post_projections <- 
  adapted_calculate_projections(parameters = post_EEM,
                                initial_condition = post_initial,
                                t_window = c(0, 29), #0 is 2016, 29 is 2045
                                scaled = FALSE,
                                species_names = c("sihek", 
                                                  pre_species),
                                mode = c("recruitment", 
                                         "removal"),
                                init_intervention_amount = c(9/divider,
                                                             0), 
                                init_intervention_timepoints = list(c(9,11),
                                                                    NA),
                                sustain_intervention_amount = c(5/divider,
                                                                -436/divider), #436 palm trees removed per month during the whole duration?
                                sustain_intervention_timepoints = 
                                  list(round(seq(13, 29, 2)),
                                       round(seq(3, 29, 0.09), 2)),
                                sustain_intervention_threshold = 
                                  c(20/divider, 
                                    10000/divider),
                                intro_species_index = c(1, 
                                                        2),
                                time_step_len = 0.01)

save(post_projections, file = "post_projections.RData")
```

```{r plot projections}
source("../../adapted functions/adapted_plot_projections.R")

load("post_projections.RData")

post_plot <- adapted_plot_projections(
  projections = post_projections,
  title = "Post-introduction system",
  multiplier = divider)


threshholds <- data.frame(yintercepts = c(86, 32876, #k
                                          20, 10000), #threshold
                          species = c("sihek", "palm trees"))

library(ggplot2)

post_plot <- post_plot +
  geom_hline(data = threshholds, aes(yintercept = yintercepts),
             color = "red", linewidth = 0.2)

post_plot

save(post_plot, file = "post_plot.RData")
```

```{r normalise projections}
load("../palm_control/palm_projections.RData")
load("post_projections.RData")
pre_system <- 
  post_projections[which(post_projections$species %in% pre_species),]

pre_system <- pre_system$pop/palm_projections$pop
rm(palm_projections)

post_projections[which(post_projections$species %in% pre_species),]$pop <-
  pre_system
rm(pre_system)

post_projections[which(is.na(post_projections$pop) & 
                         post_projections$species != "palm trees"),]

#post_projections$pop[which(is.na(post_projections$pop))] <- 0

norm_projections <- post_projections
norm_projections[which(norm_projections$species == "sihek"),]$pop <-
  norm_projections[which(norm_projections$species == "sihek"),]$pop * divider

save(norm_projections, file = "norm_projections.RData")
```

```{r plot normalised projections}
source("../../EEMtoolbox_fork/adapted functions/adapted_plot_projections.R")

norm_plot <- adapted_plot_projections(
  projections = norm_projections,
  title = "Post-introduction system, normalised with palm trees")


threshholds <- data.frame(yintercepts = c(86, 20), #threshold
                          species = "sihek")

library(ggplot2)

norm_plot <- norm_plot +
  geom_hline(data = threshholds, aes(yintercept = yintercepts),
             color = "red", linewidth = 0.2)

norm_plot

save(norm_plot, file = "norm_plot.RData")
```

```{r show both plots}
load("norm_plot.RData")
load("post_plot.RData")
load("../palm_control/palm_plot.RData")

library(gridExtra)
library(ggplot2)

grid.arrange(post_plot + theme(legend.position = "none", 
                               plot.background = element_rect(color = "black")),
             norm_plot + theme(legend.position = "none", 
                               plot.background = element_rect(color = "black")),
             palm_plot + theme(legend.position = "none", 
                               plot.background = element_rect(color = "black")),
             ncol = 3)
```


