---
title: "Pre-introduction system"
author: "Maude Vernet"
date: "2025-05-20"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r initial system description}
load("initial abundances/pre_lb.RData")
load("initial abundances/pre_ub.RData")

pre_species <- c("palm trees",
                 "seabirds",
                 "herbivorous crabs",
                 "carnivorous crabs",
                 "cane spiders",
                 "geckos",
                 "cockroaches",
                 "terrestrial arthropods",
                 "flying arthropods",
                 "native trees",
                 "others")

pre_intmatrix <- matrix(c(-1,  1, -1,  0,  0, -1, -1, -1, -1, -1, -1,
                          -1, -1,  0, -1,  0,  0,  0,  0,  0,  1, -1,
                          -1,  0, -1, -1,  0,  0,  0,  0,  0,  1,  0,
                          -1,  1,  1, -1,  0,  0,  1,  1,  1,  0,  1,
                          -1,  0,  0,  0, -1,  1,  1,  1,  1,  0,  1,
                          -1,  0,  0,  0, -1, -1,  0,  1,  1,  0, -1,
                          -1,  0,  0, -1, -1,  0, -1,  0,  0,  1,  0,
                          -1,  0,  0, -1, -1, -1,  0, -1,  0,  1,  0,
                          -1,  0,  0, -1, -1, -1,  0,  0, -1,  1,  0,
                          -1,  1, -1, -1,  0,  0,  0, -1, -1, -1, -1,
                          -1,  0,  0, -1, -1, -1,  0, -1, -1,  1, -1),
                        ncol = 11, nrow = 11,
                        dimnames = list(pre_species, pre_species),
                        byrow = TRUE)

print(pre_intmatrix)

pre_ugr <- c(3.0, 1.1, 1.5, 1.5, 0.39, 0.49, 3.0, 3.0, 3.0, 3.0, 3.0)

divider <- 4*10^6

max(pre_ub / divider)
min(pre_lb / divider)

matrix(c(pre_lb,
         pre_ub),
       nrow = 2,
       byrow = TRUE,
       dimnames = list(c("lower bounds", "upper bounds"),
                       abbreviate(pre_species)))
```

```{r EEM of initial system}
pre_EEM <- EEM(pre_intmatrix,
               upper_bounds_growth_rate = pre_ugr,
               algorithm = "SMC-EEM",
               disc_func = function(data) {
                 adapted_discrepancy_continuous_sum(
                   data,
                   target_lower = c(30000,
                                    1000000,
                                    1200000,
                                    20000,
                                    134773,
                                    183218,
                                    895134,
                                    174429,
                                    167794,
                                    630700,
                                    140717)/(4*10^6), #pre_lb and divider
                   target_upper = c(65000,
                                    1500000,
                                    1400000,
                                    38000,
                                    210946,
                                    326506,
                                    1258184,
                                    405953,
                                    275876,
                                    1892100,
                                    286332)/(4*10^6)) #pre_ub and divider
               },
               n_ensemble = 3,
               n_cores = 1,
               mcmc_trials = 40,
               p_acc_min =  0.00001)

source("../../EEMtoolbox_fork/adapted functions/add_species_names.R")

pre_EEM <- add_species_names(pre_EEM,
                             pre_species)

save(pre_EEM, file = "pre_EEM.RData")
```

```{r check if all parameters give eq within the bounds, echo=FALSE}
source("../../EEMtoolbox_fork/adapted functions/select_EEM_outputs.R")

select_EEM_outputs(pre_EEM,
                   target_lower = pre_lb/divider,
                   target_upper = pre_ub/divider)
```
